bases/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

from bases.views import Home, PaisNew, PaisView, PaisEdit, PaisDelete, \
    EstadoNew, EstadoView, EstadoEdit, EstadoDelete, CidadeNew, CidadeView, \
    CidadeEdit, CidadeDelete, OrgaoPublicoNew, OrgaoPublicoView, OrgaoPublicoEdit, \
    OrgaoPublicoDelete, ImovelNew, ImovelView, ImovelEdit, ImovelDelete, TipoObraNew, \
    TipoObraView, TipoObraEdit, TipoObraDelete, ProjetoNew, ProjetoView, ProjetoEdit, \
    ProjetoDelete, ObraNew, ObraView, ObraEdit, ObraDelete#, UploadView


urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='base/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='base/login.html'), name='logout'),    

    path('paises/', PaisView.as_view(), name='pais_list'),
    path('paises/new', PaisNew.as_view(), name='pais_new'),
    path('paises/edit/<int:pk>', PaisEdit.as_view(), name='pais_edit'),
    path('paises/delete/<int:pk>', PaisDelete.as_view(), name='pais_delete'),

    path('estados/', EstadoView.as_view(), name='estado_list'),
    path('estados/new', EstadoNew.as_view(), name='estado_new'),
    path('estados/edit/<int:pk>', EstadoEdit.as_view(), name='estado_edit'),
    path('estados/delete/<int:pk>', EstadoDelete.as_view(), name='estado_delete'),

    path('cidades/', CidadeView.as_view(), name='cidade_list'),
    path('cidades/new', CidadeNew.as_view(), name='cidade_new'),
    path('cidades/edit/<int:pk>', CidadeEdit.as_view(), name='cidade_edit'),
    path('cidades/delete/<int:pk>', CidadeDelete.as_view(), name='cidade_delete'),

    path('orgaospublicos/', OrgaoPublicoView.as_view(), name='orgaopublico_list'),
    path('orgaospublicos/new', OrgaoPublicoNew.as_view(), name='orgaopublico_new'),
    path('orgaospublicos/edit/<int:pk>', OrgaoPublicoEdit.as_view(), name='orgaopublico_edit'),
    path('orgaospublicos/delete/<int:pk>', OrgaoPublicoDelete.as_view(), name='orgaopublico_delete'),

    path('imovel/', ImovelView.as_view(), name='imovel_list'),
    path('imovel/new', ImovelNew.as_view(), name='imovel_new'),
    path('imovel/edit/<int:pk>', ImovelEdit.as_view(), name='imovel_edit'),
    path('imovel/delete/<int:pk>', ImovelDelete.as_view(), name='imovel_delete'),

    path('tipoobra/', TipoObraView.as_view(), name='tiposobra_list'),
    path('tipoobra/new', TipoObraNew.as_view(), name='tiposobra_new'),
    path('tipoobra/edit/<int:pk>', TipoObraEdit.as_view(), name='tiposobra_edit'),
    path('tipoobra/delete/<int:pk>', TipoObraDelete.as_view(), name='tiposobra_delete'),

    path('projeto/', ProjetoView.as_view(), name='projeto_list'),
    path('projeto/new', ProjetoNew.as_view(), name='projeto_new'),
    path('projeto/edit/<int:pk>', ProjetoEdit.as_view(), name='projeto_edit'),
    path('projeto/delete/<int:pk>', ProjetoDelete.as_view(), name='projeto_delete'),

    path('obra/', ObraView.as_view(), name='obra_list'),
    path('obra/new', ObraNew.as_view(), name='obra_new'),
    path('obra/edit/<int:pk>', ObraEdit.as_view(), name='obra_edit'),
    path('obra/delete/<int:pk>', ObraDelete.as_view(), name='obra_delete'),

    # path('arquivo/upload', UploadView, name ='upload_view')
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('admin/', admin.site.urls),
]

bases/views.py
from django.db import models
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from django.contrib import messages
from django.contrib.auth.mixins import \
LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin

from django.forms import model_to_dict


# Create your views here.

from django.views import generic
from django.urls import reverse_lazy
from . models import Pais, Estado, Cidade, OrgaoPublico, Imovel, TipoObra, \
    Projeto, ProjetoAnexo, Obra#, Arquivo
from . forms import PaisForm, EstadoForm, CidadeForm, OrgaoPublicoForm, ImovelForm, \
    TipoObraForm, ProjetoForm, ObraForm#, ArquivoForm


class Home(LoginRequiredMixin, generic.TemplateView):
    template_name = 'parciais/dashboard.html'
    login_url = "bases:login"   


class PaisView(LoginRequiredMixin, generic.ListView):
    #permission_required = "inv.view_categoria"
    model = Pais
    template_name = "bases/paises_list.html"
    context_object_name = "obj"
    login_url = "bases:login"    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title_page'] = "Lista de Países"
        context['entity'] = "País"
        context['breadcrumb'] = "Países"
        context['list_url'] = reverse_lazy("bases:pais_list")
        context['add_url'] = reverse_lazy("bases:pais_new")
        context['table_id'] = 'tabela_paises'
        return context
    

class PaisNew(LoginRequiredMixin, SuccessMessageMixin, generic.CreateView):
    model = Pais
    template_name = 'bases/pais_form.html'
    context_object_name = "obj"
    form_class = PaisForm
    success_url = reverse_lazy("bases:pais_list")
    login_url = "bases:login"
    success_message = "País criado com sucesso!"

    def post(self, request, *args, **kwargs):
        print(request.POST)
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                form.instance.usuario_criou = self.request.user
                data = form.save()
                data = model_to_dict(data)
            else:
                data['error'] = 'Não foi informado uma ação'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Novo País"
        context['entity'] = "País"
        context['list_url'] = self.success_url
        context['action'] = 'add'
        return context

  
class PaisEdit(SuccessMessageMixin, generic.UpdateView):
    model = Pais
    template_name = 'bases/form.html'
    context_object_name = 'obj'
    form_class = PaisForm
    success_url = reverse_lazy("bases:pais_list")
    login_url='bases:login'
    success_message = "País atualizado com sucesso!"

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        print(request.POST)
        data = {}
        try:
            action = request.POST['action']
            if action == 'update':
                form = self.get_form()
                form.instance.usuario_modificou_id = self.request.user.id
                data = form.save()
                data = model_to_dict(data)
            else:
                data['error'] = 'Não foi informado uma ação'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Editar País"
        context['entity'] = "País"
        context['list_url'] = self.success_url
        context['action'] = 'update'
        return context


class PaisDelete(LoginRequiredMixin, generic.DeleteView):
    model = Pais
    template_name = 'bases/delete.html'
    success_url = reverse_lazy('bases:pais_list')
    #permission_required = 'delete_pais'
    url_redirect = success_url

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        print('entrou no post')
        print(request.POST)
        data = {}
        try:
            self.object.delete()
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Apagar um país'
        context['entity'] = 'País'
        context['list_url'] = self.success_url
        return context


class EstadoView(LoginRequiredMixin, generic.ListView):
    #permission_required = "inv.view_categoria"
    model = Estado
    template_name = "bases/estados_list.html"
    context_object_name = "obj"
    login_url = "bases:login"    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title_page'] = "Lista de Estados"
        context['entity'] = "Estado"
        context['breadcrumb'] = "Estados"
        context['list_url'] = reverse_lazy("bases:estado_list")
        context['add_url'] = reverse_lazy("bases:estado_new")
        context['table_id'] = 'tabela_estados'
        return context
    

class EstadoNew(LoginRequiredMixin, SuccessMessageMixin, generic.CreateView):
    model = Estado
    template_name = 'bases/estado_form.html'
    context_object_name = "obj"
    form_class = EstadoForm
    success_url = reverse_lazy("bases:estado_list")
    login_url = "bases:login"
    success_message = "Estado criado com sucesso!"

    def post(self, request, *args, **kwargs):
        print(request.POST)
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                form.instance.usuario_criou = self.request.user
                data = form.save()
                data = model_to_dict(data)
            else:
                data['error'] = 'Não foi informado uma ação'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Novo Estado"
        context['entity'] = "Estado"
        context['list_url'] = self.success_url
        context['action'] = 'add'
        return context

  
class EstadoEdit(SuccessMessageMixin, generic.UpdateView):
    model = Estado
    template_name = 'bases/estado_form.html'
    context_object_name = 'obj'
    form_class = EstadoForm
    success_url = reverse_lazy("bases:estado_list")
    login_url='bases:login'
    success_message = "Estado atualizado com sucesso!"

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        print(request.POST)
        data = {}
        try:
            action = request.POST['action']
            if action == 'update':
                form = self.get_form()
                form.instance.usuario_modificou_id = self.request.user.id
                data = form.save()
                data = model_to_dict(data)
            else:
                data['error'] = 'Não foi informado uma ação'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Editar Estado"
        context['entity'] = "Estado"
        context['list_url'] = self.success_url
        context['action'] = 'update'
        return context


class EstadoDelete(LoginRequiredMixin, generic.DeleteView):
    model = Estado
    template_name = 'bases/estado_delete.html'
    success_url = reverse_lazy('bases:estado_list')
    #permission_required = 'delete_pais'
    url_redirect = success_url

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        print('entrou no post')
        print(request.POST)
        data = {}
        try:
            self.object.delete()
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Apagar um Estado'
        context['entity'] = 'Estado'
        context['list_url'] = self.success_url
        return context


class CidadeView(LoginRequiredMixin, generic.ListView):
    #permission_required = "inv.view_categoria"
    model = Cidade
    template_name = "bases/cidades_list.html"
    context_object_name = "obj"
    login_url = "bases:login"    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title_page'] = "Lista de Cidades"
        context['entity'] = "Cidade"
        context['breadcrumb'] = "Cidades"
        context['list_url'] = reverse_lazy("bases:cidade_list")
        context['add_url'] = reverse_lazy("bases:cidade_new")
        context['table_id'] = 'tabela_cidades'
        return context
    

class CidadeNew(LoginRequiredMixin, SuccessMessageMixin, generic.CreateView):
    model = Cidade
    template_name = 'bases/cidade_form.html'
    context_object_name = "obj"
    form_class = CidadeForm
    success_url = reverse_lazy("bases:cidade_list")
    login_url = "bases:login"
    success_message = "Cidade criado com sucesso!"

    def post(self, request, *args, **kwargs):

bases/templates/bases/delete.html
{% extends 'base/delete.html' %}

bases/templates/bases/estados_list.html
{% extends 'base/list.html' %}

{% block head_table %}
  <th>Id</th>
  <th>Estado</th>
  <th>Uf</th>
  <th>Pais</th>
  <th>Ativo</th>
  <th>Criado</th>
  <th>Modificado</th>
  <th class="all">Ações</th>
  {% endblock head_table %}

  {% block body_table %}
    {% for item in obj %}
        <tr>
            <td>{{item.id}}</td>
            <td>{{item.estado}}</td>
            <td>{{item.uf}}</td>
            <td>{{item.pais}}</td>
            <td>{{item.ativo|yesno:"Ativo,Inativo"}}</td>
            <td>{{item.data_criou|date:"d/m/Y H:i:s"}}</td>
            <td>{{item.data_editou|date:"d/m/Y H:i:s"}}</td>
            <td>
                <div class="btn-group">
                  {% comment %} <a href="{% url 'bases:pais_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a> {% endcomment %}
                  <a class="btn btn-success btn-circle" onclick="return abrir_modal('{% url 'bases:estado_edit' item.id %}')" href="#"><i class="far fa-edit"></i></a>
                  <a href="{% url 'bases:estado_delete' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                </div>
            </td>
        </tr>
    {% endfor %}
  {% endblock body_table %}



  
          {% comment %} <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body">
          {% if not obj %}
            <div class="alert alert-info">Não tem {{ obj.pais }}</div>
        {% else %}

        <table class="table table-striped table-hover" id="tabela_paises">
            <thead>
                <th>Id</th>
                <th>Pais</th>
                <th>Ativo</th>
                <th>Criado</th>
                <th>Modificado</th>
                <th class="all">Ações</th>
            </thead>
            <tbody>
                {% for item in obj %}
                    <tr>
                        <td>{{item.id}}</td>
                        <td>{{item.pais}}</td>
                        <td>{{item.ativo|yesno:"Ativo,Inativo"}}</td>
                        <td>{{item.data_criou|date:"d/m/Y H:i:s"}}</td>
                        <td>{{item.data_modificou|date:"d/m/Y H:i:s"}}</td>
                        <td>
                            {% comment %} <a href="{% url 'bases:pais_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                            <a class="btn btn-success btn-circle" onclick="return abrir_modal('{% url 'bases:pais_edit' item.id %}')" href="#"><i class="far fa-calendar-plus"></i></a>
                            <a href="{% url 'bases:pais_delete' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
          Footer
        </div>
        <!-- /.card-footer-->
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->
  </div>
{% endblock content %}

{% block footer_list %}
  <script src="{% static 'plugins/datatables/jquery.dataTables.min.js'%}"></script>
{% endblock footer_list %}

{% block js_page %}
<script>
  $(function(){
    $('#tabela_paises').DataTable()
  })
</script>
{% endblock js_page %}

   {% endcomment %}

bases/templates/bases/forms.html
{% extends 'base/form.html' %}

{% block content_form %}
    {{ form }}
{% endblock content_form %}

bases/templates/bases/imoveis_list.html
{% extends 'base/list.html' %}

{% block head_table %}
  <th>Id</th>
  <th>UF</th>
  <th>Cidade</th>
  <th>Imóvel</th>
  <th>Órgão Público</th>
  <th>Cep</th>
  <th>Numero</th>
  <th>Rua</th>
  <th>Bairro</th>
  <th>Complemento</th>
  <th>Ativo</th>
  <th>Criado</th>
  <th>Modificado</th>
  <th class="all">Ações</th>
  {% endblock head_table %}

  {% block body_table %}
    {% for item in obj %}
        <tr>
            <td>{{item.id}}</td>
            <td>{{item.orgao_publico.cidade.estado.uf}}</td>
            <td>{{item.orgao_publico.cidade}}</td>
            <td>{{item.imovel}}</td>
            <td>{{item.orgao_publico}}</td>
            <td>{{item.cep}}</td>
            <td>{{item.numero}}</td>
            <td>{{item.rua}}</td>
            <td>{{item.bairro}}</td>
            <td>{{item.complemento}}</td>
            <td>{{item.ativo|yesno:"Ativo,Inativo"}}</td>
            <td>{{item.data_criou|date:"d/m/Y H:i:s"}}</td>
            <td>{{item.data_editou|date:"d/m/Y H:i:s"}}</td>
            <td>
                <div class="btn-group">
                  {% comment %} <a href="{% url 'bases:pais_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a> {% endcomment %}
                  <a class="btn btn-success btn-circle" onclick="return abrir_modal('{% url 'bases:imovel_edit' item.id %}')" href="#"><i class="far fa-edit"></i></a>
                  <a href="{% url 'bases:imovel_delete' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                </div>
            </td>
        </tr>
    {% endfor %}
  {% endblock body_table %}



  
          {% comment %} <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body">
          {% if not obj %}
            <div class="alert alert-info">Não tem {{ obj.pais }}</div>
        {% else %}

        <table class="table table-striped table-hover" id="tabela_paises">
            <thead>
                <th>Id</th>
                <th>Pais</th>
                <th>Ativo</th>
                <th>Criado</th>
                <th>Modificado</th>
                <th class="all">Ações</th>
            </thead>
            <tbody>
                {% for item in obj %}
                    <tr>
                        <td>{{item.id}}</td>
                        <td>{{item.pais}}</td>
                        <td>{{item.ativo|yesno:"Ativo,Inativo"}}</td>
                        <td>{{item.data_criou|date:"d/m/Y H:i:s"}}</td>
                        <td>{{item.data_modificou|date:"d/m/Y H:i:s"}}</td>
                        <td>
                            {% comment %} <a href="{% url 'bases:pais_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                            <a class="btn btn-success btn-circle" onclick="return abrir_modal('{% url 'bases:pais_edit' item.id %}')" href="#"><i class="far fa-calendar-plus"></i></a>
                            <a href="{% url 'bases:pais_delete' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
          Footer
        </div>
        <!-- /.card-footer-->
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->
  </div>
{% endblock content %}

{% block footer_list %}
  <script src="{% static 'plugins/datatables/jquery.dataTables.min.js'%}"></script>
{% endblock footer_list %}

{% block js_page %}
<script>
  $(function(){
    $('#tabela_paises').DataTable()
  })
</script>
{% endblock js_page %}

   {% endcomment %}

bases/templates/bases/imovel_delete.html
{% extends 'base/delete.html' %}

bases/templates/bases/obras_list.html
{% extends 'base/list.html' %}

{% block head_table %}
  <th>Id</th>
  <th>País</th>
  <th>Estado</th>
  <th>Cidade</th>
  <th>Obra</th>
  <th>Projetos</th>
  <th>Status da Obra</th>
  <th>Ativo</th>
  <th>Criado</th>
  <th>Modificado</th>
  <th class="all">Ações</th>
  {% endblock head_table %}

  {% block body_table %}
    {% for item in obj %}
        <tr>
            <td>{{item.id}}</td>
            <td>{{item.imovel.orgao_publico.cidade.estado.pais}}
            <td>{{item.imovel.orgao_publico.cidade.estado}}
            <td>{{item.imovel.orgao_publico.cidade}}
            <td>{{item.obra}}</td>
            <td>{% for projeto in item.projeto.all %}
              <!--{{ projetos.projeto }}-->
              {% for arquivos in projeto.arquivo.all %}
                {{projeto.id}} -
                <a href="{{arquivos.arquivo.url}}" target="blank" >{{projeto.projeto}}/{{arquivos.arquivo.name}}</a>
                <br />
              {% endfor %}
              <br />
            {% endfor %}</td>
            <td>{{item.status_obra}}</td>
            <td>{{item.ativo|yesno:"Ativo,Inativo"}}</td>
            <td>{{item.data_criou|date:"d/m/Y H:i:s"}}</td>
            <td>{{item.data_editou|date:"d/m/Y H:i:s"}}</td>
            <td>
                <div class="btn-group">
                  {% comment %} <a href="{% url 'bases:pais_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a> {% endcomment %}
                  <!--<a class="btn btn-primary btn-circle" href="#"><i class="fa fa-eye" aria-hidden="true"></i></a>-->
                  <a class="btn btn-success btn-circle" onclick="return abrir_modal('{% url 'bases:obra_edit' item.id %}')" href="#"><i class="far fa-edit"></i></a>
                  <a href="{% url 'bases:obra_delete' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                </div>
            </td>
        </tr>
    {% endfor %}
  {% endblock body_table %}



  
          {% comment %} <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body">
          {% if not obj %}
            <div class="alert alert-info">Não tem {{ obj.pais }}</div>
        {% else %}

        <table class="table table-striped table-hover" id="tabela_paises">
            <thead>
                <th>Id</th>
                <th>Pais</th>
                <th>Ativo</th>
                <th>Criado</th>
                <th>Modificado</th>
                <th class="all">Ações</th>
            </thead>
            <tbody>
                {% for item in obj %}
                    <tr>
                        <td>{{item.id}}</td>
                        <td>{{item.pais}}</td>
                        <td>{{item.ativo|yesno:"Ativo,Inativo"}}</td>
                        <td>{{item.data_criou|date:"d/m/Y H:i:s"}}</td>
                        <td>{{item.data_modificou|date:"d/m/Y H:i:s"}}</td>
                        <td>
                            {% comment %} <a href="{% url 'bases:pais_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                            <a class="btn btn-success btn-circle" onclick="return abrir_modal('{% url 'bases:pais_edit' item.id %}')" href="#"><i class="far fa-calendar-plus"></i></a>
                            <a href="{% url 'bases:pais_delete' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
          Footer
        </div>
        <!-- /.card-footer-->
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->
  </div>
{% endblock content %}

{% block footer_list %}
  <script src="{% static 'plugins/datatables/jquery.dataTables.min.js'%}"></script>
{% endblock footer_list %}

{% block js_page %}
<script>
  $(function(){
    $('#tabela_paises').DataTable()
  })
</script>
{% endblock js_page %}

   {% endcomment %}

bases/templates/bases/pais_delete.html
{% extends 'base/delete.html' %}

bases/templates/bases/projeto_delete.html
{% extends 'base/delete.html' %}

bases/templates/bases/tipoprojeto_delete.html
{% extends 'base/delete.html' %}

bases/templates/bases/tipoprojeto_form.html
{% extends 'base/form.html' %}

{% block content_form %}
    {{ form }}
{% endblock content_form %}

bases/templates/bases/tiposobra_delete.html
{% extends 'base/delete.html' %}

bases/templates/bases/upload_arquivo.html
<form method ='post' enctype ="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value = "Submit">
</form>