bases/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

from bases.views import Home, PaisNew, PaisView, PaisEdit, PaisDelete, \
    EstadoNew, EstadoView, EstadoEdit, EstadoDelete, CidadeNew, CidadeView, \
    CidadeEdit, CidadeDelete, OrgaoPublicoNew, OrgaoPublicoView, OrgaoPublicoEdit, \
    OrgaoPublicoDelete, ImovelNew, ImovelView, ImovelEdit, ImovelDelete, TipoObraNew, \
    TipoObraView, TipoObraEdit, TipoObraDelete, ProjetoNew, ProjetoView, ProjetoEdit, \
    ProjetoDelete, ObraNew, ObraView, ObraEdit, ObraDelete#, UploadView


urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='base/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='base/login.html'), name='logout'),    

    path('paises/', PaisView.as_view(), name='pais_list'),
    path('paises/new', PaisNew.as_view(), name='pais_new'),
    path('paises/edit/<int:pk>', PaisEdit.as_view(), name='pais_edit'),
    path('paises/delete/<int:pk>', PaisDelete.as_view(), name='pais_delete'),

    path('estados/', EstadoView.as_view(), name='estado_list'),
    path('estados/new', EstadoNew.as_view(), name='estado_new'),
    path('estados/edit/<int:pk>', EstadoEdit.as_view(), name='estado_edit'),
    path('estados/delete/<int:pk>', EstadoDelete.as_view(), name='estado_delete'),

    path('cidades/', CidadeView.as_view(), name='cidade_list'),
    path('cidades/new', CidadeNew.as_view(), name='cidade_new'),
    path('cidades/edit/<int:pk>', CidadeEdit.as_view(), name='cidade_edit'),
    path('cidades/delete/<int:pk>', CidadeDelete.as_view(), name='cidade_delete'),

    path('orgaospublicos/', OrgaoPublicoView.as_view(), name='orgaopublico_list'),
    path('orgaospublicos/new', OrgaoPublicoNew.as_view(), name='orgaopublico_new'),
    path('orgaospublicos/edit/<int:pk>', OrgaoPublicoEdit.as_view(), name='orgaopublico_edit'),
    path('orgaospublicos/delete/<int:pk>', OrgaoPublicoDelete.as_view(), name='orgaopublico_delete'),

    path('imovel/', ImovelView.as_view(), name='imovel_list'),
    path('imovel/new', ImovelNew.as_view(), name='imovel_new'),
    path('imovel/edit/<int:pk>', ImovelEdit.as_view(), name='imovel_edit'),
    path('imovel/delete/<int:pk>', ImovelDelete.as_view(), name='imovel_delete'),

    path('tipoobra/', TipoObraView.as_view(), name='tiposobra_list'),
    path('tipoobra/new', TipoObraNew.as_view(), name='tiposobra_new'),
    path('tipoobra/edit/<int:pk>', TipoObraEdit.as_view(), name='tiposobra_edit'),
    path('tipoobra/delete/<int:pk>', TipoObraDelete.as_view(), name='tiposobra_delete'),

    path('projeto/', ProjetoView.as_view(), name='projeto_list'),
    path('projeto/new', ProjetoNew.as_view(), name='projeto_new'),
    path('projeto/edit/<int:pk>', ProjetoEdit.as_view(), name='projeto_edit'),
    path('projeto/delete/<int:pk>', ProjetoDelete.as_view(), name='projeto_delete'),

    path('obra/', ObraView.as_view(), name='obra_list'),
    path('obra/new', ObraNew.as_view(), name='obra_new'),
    path('obra/edit/<int:pk>', ObraEdit.as_view(), name='obra_edit'),
    path('obra/delete/<int:pk>', ObraDelete.as_view(), name='obra_delete'),

    # path('arquivo/upload', UploadView, name ='upload_view')
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('admin/', admin.site.urls),
]

templates/base/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<title>OmegaPlan | {% block titulo %}{% endblock titulo %}</title>
{% include 'parciais/header.html' %}

{% block head_list %}{% endblock head_list %}

<body class="hold-transition sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">
  <!-- Navbar -->
  {% block navbar %}
  {% include 'parciais/navbar.html' %}
  {% endblock navbar %}
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  {% block menu %}  
  {% include 'parciais/menu.html' %}
  {% endblock menu %}  

  <!-- Content Wrapper. Contains page content -->
  {% block content %}

  {% endblock content %}

  {% block login %}
  {% endblock login %}
  <!-- /.content-wrapper -->
  {% block footer %}
  {% include 'parciais/footer.html' %}
  {% endblock footer %}  

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->



<div class="modal fade" id="popup"></div>

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %}"></script>

<script src="{% static 'plugins/jquery_confirm/jquery-confirm.min.js' %}"></script>
<script src="{% static 'plugins/sweetalert2/sweetalert2.min.js' %}"></script>

<script src="{% static 'js/functions.js' %}"></script>

{% block footer_list %}
  
{% endblock footer_list %}


{% block control_modal %}

  <script>
    function abrir_modal(url){
      $('#popup').load(url, function(){
        $(this).modal({
          backdrop:'static',
          keyboard: false
        })
        $(this).modal('show')
      })
      return false
    }

    function fechar_modal(){
      $('#popup').modal('hide')
      return false
    }

    function mensagem(msg, cor='green'){
      if(cor=='success'){
        cor = 'green'
      } else {
        cor = 'red'
      }
      $.alert({
        title:'',
        theme:'material',
        type:cor,
        content:msg
      })
    }

    {% if messages %}
      {% for message in messages %}
        console.log('{{ message.tags }}')
        mensagem("{{ message }}", "{{ message.tags }}")
      {% endfor %}
    {% endif %}

  </script>

  {% endblock control_modal %}


{% block js_page %}{% endblock js_page %}
</body>
</html>

templates/base/delete.html
{% extends 'base/base.html' %}





{% block content %}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">

    <form id="form_delete" method="post" action=".">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="fas fa-trash"></i>
                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                <input type="hidden" name="action" value="{{ action }}">
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-ban"></i> Houve um erro</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                <div class="alert alert-danger alert-dismissible">
                    <h5><i class="icon fas fa-ban"></i> Notificação!</h5>
                    Tem certeza que deseja eliminar o registro N°{{ object.id }}?
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary btn-flat">
                    <i class="fas fa-save"></i> Sim, aceitar
                </button>
                <a href="{{ list_url }}" class="btn btn-danger btn-flat">
                    <i class="fas fa-times"></i> Cancelar
                </a>
            </div>
        </div>
    </form>
    </div>
    </div>
    </div>
    {% endblock %}

{% block js_page %}    
<script>
    $('#form_delete').on('submit', function (e) {
        e.preventDefault();
        var parameters = new FormData(this);
        
        let url = window.location.pathname //+ '{{object.id}}'
        submit_with_ajax(url, 'Notificação', 'Tem certeza que quer apagar o siguiente registro?', parameters, function () {
            Swal.fire({
                title: 'Alerta',
                text: 'Registro eliminado corretamente',
                icon: 'success',
                timer: 2000,
                onClose: () => {
                    location.href = '{{ list_url }}';
                }
            }).then((result) => {

            });
        });
    });
</script>
{% endblock js_page %}

templates/base/form.html
{% comment %} <div class="modal-dialog modal-lg">
    <div class="modal-content">
        {% if obj %}
        <form method="POST" role="form" action="{% url 'bases:pais_edit' obj.id %}">
        {% else %}
        <form method="POST" role="form" action="{% url 'bases:pais_new' %}">
        {% endif %}
            {% csrf_token %}
            <input type="hidden" id="action" name="action" value="{{ action }}">
            <div class="col-xl-12 col-md-12 mb-12">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                <h2>{% if obj %} Editar {% else %} Adicionar {% endif %} {{ entity }}</h2>
                            </div>
                            <div class="dropdown-divider"></div>
                            <div class="row">
                                {% block content_form %} {% endblock content_form %}
                            </div>
                            <div class="dropdown-divider"></div>
                            <div class="row">
                                <div class="col">
                                    <button type="submit" class="btn btn-danger"><span class="fa fa-save"> Salvar</span></button>
                                    <button type="button" class="btn btn-success" onclick="return fechar_modal()"> Cancelar</button>        
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
 {% endcomment %}

<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <form method="post" action="." enctype="multipart/form-data">
        {% comment %} {% if obj %}
        <form method="POST" role="form" action="{% url 'bases:pais_edit' obj.id %}">
        {% else %}
        <form method="POST" role="form" action="{% url 'bases:pais_new' %}">
        {% endif %} {% endcomment %}
            {% csrf_token %}
            <input type="hidden" id="action" name="action" value="{{ action }}">
            <div class="card {%if obj%}card-primary{%else%} card-success{%endif%}">
                
                <div class="card-header">
                    <h3 class="card-title">{% if obj %} Editar {% else %} Adicionar {% endif %} {{ entity }}</h3>

                    <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button onclick="return fechar_modal()" type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                    </div>
                </div>

                <div class="card-body">
                    {% block content_form %} {% endblock content_form %}
                </div>

                <!-- /.card-body -->
                <div class="card-footer">
                    <div class="col">
                        <button type="submit" class="btn btn-danger"><span class="fa fa-save"> Salvar</span></button>
                        <button type="button" class="btn btn-success" onclick="return fechar_modal()"> Cancelar</button>        
                    </div>
                </div>
                <!-- /.card-footer-->
            </div>
        </div>
    </div>
</div>


<script>
$('form').on('submit', function (e) {
            e.preventDefault();
            var parameters = new FormData(this);
            let url = window.location.pathname
            if($('#action').val() == 'add'){
                url += 'new'
            } else if($('#action').val() == 'update'){
                url += 'edit/' + '{{ obj.id }}' 
            }
            //submit_with_ajax(window.location.pathname, 'Notificação', 'Tem certeza que quer realizar essa ação?', parameters, function () {
            submit_with_ajax(url, 'Notificação', 'Tem certeza que quer realizar essa ação?', parameters, function () {
                location.href = '{{ list_url }}';
            });
        });
</script>

{% block js_page %}{% endblock js_page %}

templates/base/form_.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        {% if obj %}
        <form method="POST" role="form" action="{% url 'bases:pais_edit' obj.id %}">
        {% else %}
        <form method="POST" role="form" action="{% url 'bases:pais_new' %}">
        {% endif %}
            {% csrf_token %}
            <input type="hidden" id="action" name="action" value="{{ action }}">
            <div class="col-xl-12 col-md-12 mb-12">
                {% if obj %}
                <div class="card border-left-warning shadow h-100 py-2">
                {% else %}
                <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                    <h2>{% if obj %} Editar {% else %} Adicionar {% endif %} {{ entity }}</h2>
                                </div>
                                <div class="dropdown-divider"></div>
                                <div class="row">
                                    {% block content_form %} {% endblock content_form %}
                                </div>
                                <div class="dropdown-divider"></div>
                                <div class="row">
                                    <div class="col">
                                        <button type="submit" class="btn btn-danger"><span class="fa fa-save"> Salvar</span></button>
                                        <button type="button" class="btn btn-success" onclick="return fechar_modal()"> Cancelar</button>        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                </div>
        </form>
    </div>
</div>








<script>
$('form').on('submit', function (e) {
            e.preventDefault();
            var parameters = new FormData(this);
            let url = window.location.pathname
            if($('#action').val() == 'add'){
                url += 'new'
            } else if($('#action').val() == 'update'){
                url += 'edit/' + '{{ obj.id }}' 
            }
            //submit_with_ajax(window.location.pathname, 'Notificação', 'Tem certeza que quer realizar essa ação?', parameters, function () {
            submit_with_ajax(url, 'Notificação', 'Tem certeza que quer realizar essa ação?', parameters, function () {
                location.href = '{{ list_url }}';
            });
        });
</script>

templates/base/list.html
{% extends 'base/base.html' %}

{% load static %}

{% block head_list %}
<!-- DataTables -->
<link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">
  
{% endblock head_list %}

{% block titulo %}
    {{ breadcrumb }}
{% endblock titulo %}

{% block content %}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{ title_page }}</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="/">Home</a></li>
              <li class="breadcrumb-item active"><a href="{{list_url}}">{{ breadcrumb }}</a></li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">
          <a class="btn btn-success" onclick="return abrir_modal('{{add_url}}')" href="#"><i class="far fa-calendar-plus"> Adicionar {{ entity }}</i></a>
          </h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body">
          {% if not obj %}
            <div class="alert alert-info">Não tem {{ breadcrumb }}</div>
        {% else %}

        <table class="table table-striped table-hover table-responsive" id="{{table_id}}">
            <thead>
                {% block head_table %}
                {% endblock head_table %}
            </thead>
            <tbody>
                {% block body_table %}
                {% endblock body_table %}
            </tbody>
        </table>
        {% endif %}
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
          Footer
        </div>
        <!-- /.card-footer-->
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->
  </div>
{% endblock content %}

{% block footer_list %}
<!-- DataTables  & Plugins -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
{% endblock footer_list %}

{% block js_page %}
<script>
  $(function(){
    $('#'+'{{ table_id }}').DataTable({
      pageLength: 5,
      lengthMenu: [[5,20,100,-1],["Pouco","Médio","Muito","Todos"]],
      language: { 
        info: "Mostrando _START_ a _END_ de _TOTAL_ registros", 
        infoEmpty: "Sem registros", 
        infoFiltered: 'filtrados de _MAX_ registros', 
        emptyTable: "Nenhum registro avaliado na tabela", 
        zeroRecords: "Nenhum registro encontrado para a busca", 
        lengthMenu: "Mostrando _MENU_ registros", 
        searchPlaceHolder: 'Filtro', 
        search: 'Digite sua busca:', 
        paginate: { 
            first: '<<', 
            last: '>>', 
            previous: '<', 
            next: '>' 
        } 
      } 
    })
    
  })
</script>
{% endblock js_page %}

templates/base/login.html
{% extends 'base/base.html' %}
{% block navbar %} {% endblock navbar %}
{% block menu %} {% endblock menu %}
{% comment %} {% block content %}  {% endblock content %} {% endcomment %}
{% block footer %} {% endblock footer %}  
{% block login %}
    <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-6 col-lg-12 col-md-6">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              {% comment %} <div class="col-lg-6 d-none d-lg-block bg-login-image"></div> {% endcomment %}
              <div class="col-lg-12">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Login</h1>
                    <small>
                        {% if form.errors %}
                            {% for field in form %}
                                {% if field.errors %}
                                    {% for error in field.errors  %}
                                        {{ error|escape}}
                                    {% endfor %}
                                {% endif %}
                            {% endfor %}
                        {% endif %}

                        {% if form.non_field_errors %}
                            {% for error in form.non_field_errors %}
                                {{ error|escape}}
                            {% endfor %}
                        {% endif %}
                    </small>
                  </div>
                  <form class="user" method="POST">
                      {% csrf_token %}
                    <div class="form-group">
                      <input type="text" class="form-control form-control-user" id="id_username" name="username" aria-describedby="emailHelp" placeholder="Enter Email Address...">
                    </div>
                    <div class="form-group">
                      <input type="password" class="form-control form-control-user" id="id_password" name="password" placeholder="Password">
                    </div>
                    <div class="form-group">
                      <div class="custom-control custom-checkbox small">
                        <input type="checkbox" class="custom-control-input" id="customCheck">
                        <label class="custom-control-label" for="customCheck">Remember Me</label>
                      </div>
                    </div>
                    {#{ form.as_p}#}
                    <button type="submit" class="btn btn-primary btn-user btn-block">Entrar</button>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>
{% endblock login %}



{% block js_page %}
<script>
{% if form.errors %}
    {% for field in form %}
            {% if field.errors %}
                {% for error in field.errors  %}
                    mensagem('{{ error|escape}}', 'red')
                {% endfor %}
            {% endif %}
        {% endfor %}
    {% endif %}

    {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
            mensagem('{{ error|escape}}', 'red')
        {% endfor %}
    {% endif %}
</script>
{% endblock js_page %}