bases/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

from bases.views import Home, PaisNew, PaisView, PaisEdit, PaisDelete, \
    EstadoNew, EstadoView, EstadoEdit, EstadoDelete, CidadeNew, CidadeView, \
    CidadeEdit, CidadeDelete, OrgaoPublicoNew, OrgaoPublicoView, OrgaoPublicoEdit, \
    OrgaoPublicoDelete, ImovelNew, ImovelView, ImovelEdit, ImovelDelete, TipoObraNew, \
    TipoObraView, TipoObraEdit, TipoObraDelete, ProjetoNew, ProjetoView, ProjetoEdit, \
    ProjetoDelete, ObraNew, ObraView, ObraEdit, ObraDelete#, UploadView


urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='base/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='base/login.html'), name='logout'),    

    path('paises/', PaisView.as_view(), name='pais_list'),
    path('paises/new', PaisNew.as_view(), name='pais_new'),
    path('paises/edit/<int:pk>', PaisEdit.as_view(), name='pais_edit'),
    path('paises/delete/<int:pk>', PaisDelete.as_view(), name='pais_delete'),

    path('estados/', EstadoView.as_view(), name='estado_list'),
    path('estados/new', EstadoNew.as_view(), name='estado_new'),
    path('estados/edit/<int:pk>', EstadoEdit.as_view(), name='estado_edit'),
    path('estados/delete/<int:pk>', EstadoDelete.as_view(), name='estado_delete'),

    path('cidades/', CidadeView.as_view(), name='cidade_list'),
    path('cidades/new', CidadeNew.as_view(), name='cidade_new'),
    path('cidades/edit/<int:pk>', CidadeEdit.as_view(), name='cidade_edit'),
    path('cidades/delete/<int:pk>', CidadeDelete.as_view(), name='cidade_delete'),

    path('orgaospublicos/', OrgaoPublicoView.as_view(), name='orgaopublico_list'),
    path('orgaospublicos/new', OrgaoPublicoNew.as_view(), name='orgaopublico_new'),
    path('orgaospublicos/edit/<int:pk>', OrgaoPublicoEdit.as_view(), name='orgaopublico_edit'),
    path('orgaospublicos/delete/<int:pk>', OrgaoPublicoDelete.as_view(), name='orgaopublico_delete'),

    path('imovel/', ImovelView.as_view(), name='imovel_list'),
    path('imovel/new', ImovelNew.as_view(), name='imovel_new'),
    path('imovel/edit/<int:pk>', ImovelEdit.as_view(), name='imovel_edit'),
    path('imovel/delete/<int:pk>', ImovelDelete.as_view(), name='imovel_delete'),

    path('tipoobra/', TipoObraView.as_view(), name='tiposobra_list'),
    path('tipoobra/new', TipoObraNew.as_view(), name='tiposobra_new'),
    path('tipoobra/edit/<int:pk>', TipoObraEdit.as_view(), name='tiposobra_edit'),
    path('tipoobra/delete/<int:pk>', TipoObraDelete.as_view(), name='tiposobra_delete'),

    path('projeto/', ProjetoView.as_view(), name='projeto_list'),
    path('projeto/new', ProjetoNew.as_view(), name='projeto_new'),
    path('projeto/edit/<int:pk>', ProjetoEdit.as_view(), name='projeto_edit'),
    path('projeto/delete/<int:pk>', ProjetoDelete.as_view(), name='projeto_delete'),

    path('obra/', ObraView.as_view(), name='obra_list'),
    path('obra/new', ObraNew.as_view(), name='obra_new'),
    path('obra/edit/<int:pk>', ObraEdit.as_view(), name='obra_edit'),
    path('obra/delete/<int:pk>', ObraDelete.as_view(), name='obra_delete'),

    # path('arquivo/upload', UploadView, name ='upload_view')
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('admin/', admin.site.urls),
]

templates/parciais/dashboard.html
{% extends 'base/base.html' %}

{% load static %}

{% block titulo %}
    Dashboard
{% endblock titulo %}

bla bla

{% block content %}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Dashboard</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Dashboard</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Title</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body">
          Start creating your amazing application!
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
          Footer
        </div>
        <!-- /.card-footer-->
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->
  </div>
{% endblock content %}

templates/parciais/footer.html
{% load static %}
<footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Versão</b> 1.0.0
    </div>
    <strong>Copyright &copy; 2020-2021 <a href="#">Omegaplan</a>.</strong> All rights reserved.
</footer>

templates/parciais/header.html
{%load static%}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">

  <link href="{% static 'plugins/jquery_confirm/jquery-confirm.min.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/sweetalert2/sweetalert2.min.css' %}" rel="stylesheet">
</head>

templates/parciais/home.html
{% extends 'base.html' %}

templates/parciais/menu.html
{% load static %}
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="../../" class="brand-link">
      <img src="{% static 'dist/img/AdminLTELogo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">Omegaplan</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{% static 'dist/img/user2-160x160.jpg' %}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">{{ request.user.username }} - {{ request.user.id}}</a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      {% comment %} <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div> {% endcomment %}

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Cadastros
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'bases:pais_list' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Países</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'bases:estado_list' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Estados</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'bases:cidade_list' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Cidades</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'bases:orgaopublico_list' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Órgãos Públicos</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'bases:imovel_list' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Imóveis</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'bases:tiposobra_list' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Tipos de Obra</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'bases:obra_list' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Obras</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'bases:projeto_list' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Projetos</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="/login" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Logar</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="/logout" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Sair</p>
                </a>
              </li>
            </ul>
          </li>

        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

templates/parciais/navbar.html
{% load static %}
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url "bases:home" %}" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      {% comment %} <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li> {% endcomment %}

      <!-- Messages Dropdown Menu -->
      {% comment %} <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{% static 'dist/img/user1-128x128.jpg' %}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{% static 'dist/img/user8-128x128.jpg' %}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{% static 'dist/img/user3-128x128.jpg' %}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li> {% endcomment %}
      <!-- Notifications Dropdown Menu -->
      {% comment %} <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li> {% endcomment %}
      {% comment %} <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li> {% endcomment %}
    </ul>
  </nav>